FROM registry.fedoraproject.org/fedora-minimal:latest

RUN microdnf -y install python3 python-fastapi tar vi pip
RUN pip install uvicorn[standard] unalix python-multipart

RUN mkdir /opt/app
WORKDIR /opt/app

VOLUME [ "/opt/app" ]
EXPOSE 8000

CMD [ "/usr/local/bin/uvicorn", "--host", "0.0.0.0", "--reload", "main:app" ]
