FROM fedora-minimal

RUN microdnf -y install python3 python-fastapi tar vi pip
RUN pip install uvicorn[standard] unalix python-multipart

RUN mkdir /opt/app
WORKDIR /opt/app

VOLUME [ "/opt/app" ]
EXPOSE 8000

CMD [ "/bin/bash" ]
